import {
  HomeOutlined,
  MobileOutlined,
  LoginOutlined,
  UploadOutlined,
  SearchOutlined,
  DeleteOutlined,
  EditOutlined,
  EyeOutlined,
  InboxOutlined,
  FileAddOutlined,
  LockOutlined,
  MailOutlined,
  LockTwoTone,
  MailTwoTone,
  MobileTwoTone,
  PushpinTwoTone,
  ScheduleTwoTone,
  SmileTwoTone,
} from "@ant-design/icons";

export {
  HomeOutlined,
  MobileOutlined,
  LoginOutlined,
  UploadOutlined,
  SearchOutlined,
  DeleteOutlined,
  EditOutlined,
  EyeOutlined,
  InboxOutlined,
  FileAddOutlined,
  LockOutlined,
  MailOutlined,
  LockTwoTone,
  MailTwoTone,
  MobileTwoTone,
  PushpinTwoTone,
  ScheduleTwoTone,
  SmileTwoTone,
};
